---
language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - echo "[defaults]" > ansible.cfg
  - echo "roles_path = ../" >> ansible.cfg

script:
  # Check syntax
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"

  # Idempotency
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check distro
  - sudo lsb_release -a
  # Install some packages
  - sudo apt-get update -qq
  - sudo apt-cache madison quagga
  - sudo apt-get install -y quagga
  - sudo apt-get install -y midolman
